name: DynamicCOREPlus
version: "1.0.0"
main: com.dynamiccore.DynamicCOREPlus
api-version: "1.21"
authors:
  - itz_arnavfalke197
description: An advanced all-in-one Minecraft SMP essential plugin surpassing EssentialsX with integrated player, moderation, utility, and quality of life features, including built-in economy system.
website: https://example.com
softdepend: [Vault]

commands:
  home:
    description: Teleport to your home
    usage: /home [name]
    permission: dynamiccore+.essentials.home
  sethome:
    description: Set your home location
    usage: /sethome [name]
    permission: dynamiccore+.essentials.sethome
  delhome:
    description: Delete a home location
    usage: /delhome [name]
    permission: dynamiccore+.essentials.delhome
  tpa:
    description: Request teleport to another player
    usage: /tpa <player>
    permission: dynamiccore+.essentials.tpa
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: dynamiccore+.essentials.tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
    permission: dynamiccore+.essentials.tpdeny
  tpahere:
    description: Request teleport to you
    usage: /tpahere <player>
    permission: dynamiccore+.essentials.tpahere
  warp:
    description: Teleport to a warp point
    usage: /warp <name>
    permission: dynamiccore+.essentials.warp
  setwarp:
    description: Set a warp point
    usage: /setwarp <name>
    permission: dynamiccore+.moderation.setwarp
  delwarp:
    description: Delete a warp point
    usage: /delwarp <name>
    permission: dynamiccore+.moderation.delwarp
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: dynamiccore+.essentials.spawn
  setspawn:
    description: Set the spawn location
    usage: /setspawn
    permission: dynamiccore+.moderation.setspawn
  back:
    description: Return to your last death location
    usage: /back
    permission: dynamiccore+.essentials.back
  rtp:
    description: Random teleport
    usage: /rtp
    permission: dynamiccore+.essentials.rtp
  afk:
    description: Toggle AFK status
    usage: /afk
    permission: dynamiccore+.essentials.afk
  bal:
    description: Check your balance
    usage: /bal [player]
    permission: dynamiccore+.economy.bal
  pay:
    description: Pay another player
    usage: /pay <player> <amount>
    permission: dynamiccore+.economy.pay
  daily:
    description: Claim daily reward
    usage: /daily
    permission: dynamiccore+.economy.daily
  eco:
    description: Manage player economy (admin)
    usage: /eco <give|take|set|reset> <player> <amount>
    permission: dynamiccore+.moderation.economy.admin
  mute:
    description: Mute a player
    usage: /mute <player> [time]
    permission: dynamiccore+.moderation.mute
  ban:
    description: Ban a player
    usage: /ban <player> [reason]
    permission: dynamiccore+.moderation.ban
  kick:
    description: Kick a player
    usage: /kick <player> [reason]
    permission: dynamiccore+.moderation.kick
  freeze:
    description: Freeze a player
    usage: /freeze <player>
    permission: dynamiccore+.moderation.freeze
  god:
    description: Toggle god mode
    usage: /god [player]
    permission: dynamiccore+.moderation.god
  clear:
    description: Clear inventory
    usage: /clear [player]
    permission: dynamiccore+.moderation.clear
  broadcast:
    description: Broadcast a message
    usage: /broadcast <message>
    permission: dynamiccore+.moderation.broadcast
  staffchat:
    description: Send a staff chat message
    usage: /staffchat <message>
    permission: dynamiccore+.moderation.staffchat
  repair:
    description: Repair an item
    usage: /repair
    permission: dynamiccore+.utility.repair
  enchant:
    description: Enchant an item
    usage: /enchant <enchantment> <level>
    permission: dynamiccore+.utility.enchant
  rename:
    description: Rename an item
    usage: /rename <name>
    permission: dynamiccore+.utility.rename
  stats:
    description: View player stats
    usage: /stats [player]
    permission: dynamiccore+.utility.stats
  leaderboard:
    description: View leaderboards
    usage: /leaderboard <type>
    permission: dynamiccore+.utility.leaderboard
  invsee:
    description: View a player's inventory
    usage: /invsee <player>
    permission: dynamiccore+.moderation.invsee
  dcore:
    description: Reload plugin
    usage: /dcore reload
    permission: dynamiccore+.moderation.dcore
permissions:
  dynamiccore+.*:
    description: All Dynamic CORE+ permissions
    children:
      dynamiccore+.moderation.*: true
      dynamiccore+.essentials.*: true
      dynamiccore+.economy.*: true
      dynamiccore+.utility.*: true
      dynamiccore+.qol.*: true
    default: op
  dynamiccore+.moderation.*:
    description: All moderation permissions for Dynamic CORE+
    children:
      dynamiccore+.moderation.mute: true
      dynamiccore+.moderation.ban: true
      dynamiccore+.moderation.kick: true
      dynamiccore+.moderation.freeze: true
      dynamiccore+.moderation.god: true
      dynamiccore+.moderation.clear: true
      dynamiccore+.moderation.broadcast: true
      dynamiccore+.moderation.staffchat: true
      dynamiccore+.moderation.setwarp: true
      dynamiccore+.moderation.setspawn: true
      dynamiccore+.moderation.invsee: true
      dynamiccore+.moderation.dcore: true

    default: op
  dynamiccore+.essentials.*:
    description: All essentials permissions for Dynamic CORE+
    children:
      dynamiccore+.essentials.home: true
      dynamiccore+.essentials.sethome: true
      dynamiccore+.essentials.delhome: true
      dynamiccore+.essentials.tpa: true
      dynamiccore+.essentials.tpaccept: true
      dynamiccore+.essentials.tpdeny: true
      dynamiccore+.essentials.tpahere: true
      dynamiccore+.essentials.warp: true
      dynamiccore+.essentials.spawn: true
      dynamiccore+.essentials.back: true
      dynamiccore+.essentials.rtp: true
      dynamiccore+.essentials.afk: true
    default: true
  dynamiccore+.economy.*:
    description: All economy permissions for Dynamic CORE+
    children:
      dynamiccore+.economy.bal: true
      dynamiccore+.economy.pay: true
      dynamiccore+.economy.daily: true
    default: true
  dynamiccore+.utility.*:
    description: All utility permissions for Dynamic CORE+
    children:
      dynamiccore+.utility.repair: true
      dynamiccore+.utility.enchant: true
      dynamiccore+.utility.rename: true
      dynamiccore+.utility.stats: true
      dynamiccore+.utility.leaderboard: true
    default: true
  dynamiccore+.qol.*:
    description: All quality of life permissions for Dynamic CORE+
    children: {}
    default: true
